{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.my_flutter_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 13046151,
          "sha512": "402e6a64ab76167fe2ed72ab0aa29e6a366e1079041d73cbc3052d5d17c638db475a2e594d04b54c2dce5d9446d8d5d8b342c5f7228638140f3a714df500bbe4",
          "sha256": "c844f4da4b294ff900e42ceca47842fd4faabb3ada3c3c4e09f5c25a4c13d3c6",
          "sha1": "6f4814eed73794fa1becc1131776e3601d030a87",
          "md5": "2eb2bd87e7ac20b3d06d27a8facc6892"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 13046151,
          "sha512": "402e6a64ab76167fe2ed72ab0aa29e6a366e1079041d73cbc3052d5d17c638db475a2e594d04b54c2dce5d9446d8d5d8b342c5f7228638140f3a714df500bbe4",
          "sha256": "c844f4da4b294ff900e42ceca47842fd4faabb3ada3c3c4e09f5c25a4c13d3c6",
          "sha1": "6f4814eed73794fa1becc1131776e3601d030a87",
          "md5": "2eb2bd87e7ac20b3d06d27a8facc6892"
        }
      ]
    }
  ]
}
