{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.my_flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3890169,
          "sha512": "d67ff0d055d5b444f2d4928736ab3639514eb1b31d9ae0059ea0df819754a9bd49de15030b008d009ca7ac11930436db43fd12e4ee3425fa32bbefec40a5e1b7",
          "sha256": "bc3c47e7156c5ad113bb3cca85f04b24f348d38b502bd2d0d050056788b0e915",
          "sha1": "d7be672c5347ea06cb1b62b72bc80b4f468caaef",
          "md5": "964dff0ae8e4b40961cba6fe0626e262"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3890169,
          "sha512": "d67ff0d055d5b444f2d4928736ab3639514eb1b31d9ae0059ea0df819754a9bd49de15030b008d009ca7ac11930436db43fd12e4ee3425fa32bbefec40a5e1b7",
          "sha256": "bc3c47e7156c5ad113bb3cca85f04b24f348d38b502bd2d0d050056788b0e915",
          "sha1": "d7be672c5347ea06cb1b62b72bc80b4f468caaef",
          "md5": "964dff0ae8e4b40961cba6fe0626e262"
        }
      ]
    }
  ]
}
